### ISSUE TITLE
Finish unit tests

### ISSUE THREAD

**Issue by chrisjonesBSU** [cmelab/hoomd-organics#16]
There are still some gaps in the unit test.

- Welding utils file (Done)
- Utils with actions
- Tensile test  (Done)
- Charge scaling
- system.py (raising units exceptions)

**Comment by chrisjonesBSU** [comment]
#29 finished unit tests for welding and tensile simulations.

**Comment by marjanAlbouye** [comment]
#34 finished unit tests for utils actions, ff_utils and system ref units.
